added ErrorBoundary component
AntonAgaro/Starship pull request #10
Opened 2023-09-19 17:06 UTC by Dunai1907

### Какую задачу решаем
Добавить ErrorBoundary. При возникновении ошибки в компоненте приложение не падает, ошибка обработана в ErrorBoundary.

Когда будут компоненты, обернем нужные.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-09-19 19:56 UTC, B-rnCorn approved these changes

2023-09-20 07:47 UTC, IvanPeleshok commented on packages/client/src/Modules/ErrorBoundary/ErrorBoundary.tsx
> +const ErrorBoundary = ({ children }: ErrorBoundaryProps) => {
ErrorBoundary единственный компонент, который не может быть написать в функциональным компонентом в рамках реакта

Если честно, то впервые вижу такое решение с подпиской на событие error

Предлагаю реализовать классическим решением следующим образом:
<img width="577" alt="Снимок экрана 2023-09-20 в 11 46 28" src="https://github.com/AntonAgaro/Starship/assets/70073003/9df0e6ad-fbb1-46b8-adf7-be89225a6c96">

(см. https://www.geeksforgeeks.org/react-js-error-boundaries/)

Вот ещё пример: https://medium.com/bb-tutorials-and-thoughts/how-to-create-an-error-boundary-in-react-applications-d39886a516df

2023-09-20 07:49 UTC, IvanPeleshok requested changes
Проделана большая работа!

Интересный подход, но всё-таки предлагается написать классическим решением обработку исключений в компонентах

В комментарии указал примеры

Также необходимо пофиксить чек на линтер

2023-09-21 06:19 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув :)

2023-09-21 21:13 UTC, merged