Sta 33 add redux storage
AntonAgaro/Starship pull request #18
Opened 2023-10-01 21:40 UTC by burdenkof

### Какую задачу решаем
данные хранятся и обрабатываются через Redux; 

 состояния приложения хранятся в сторе

Добавить в проект redux-toolkit. (По желанию) 

Добавить слайс для юзера (к примеру). 

После авторизации класть информацию о юзере в слайс.

### Скриншоты/видяшка (если есть)
[recording-2023-09-22-04-18-08_Editwebm.webm](https://github.com/AntonAgaro/Starship/assets/13813730/2ef1367f-a81a-4161-b29f-1a5d2a0e54a2)
### TBD (если есть)

2023-10-01 21:43 UTC, burdenkof commented
Плз не делайте мердж даже если не будет замечаний, хотелось бы сдать на проверку в практикум таск

2023-10-02 05:39 UTC, killank commented on packages/client/src/Modules/SignUpForm/signUpForm.tsx
> +        const profile = await auth.getProfile()
Работу с запросами лучше перенести в Саги

2023-10-02 05:39 UTC, killank commented on packages/client/src/Redux/userState.tsx
> +const initialState = null as TProfileInfo | null
Лучше разделить типизацию стейта и его инициализацию, чтобы код был более читаемым.
Вынеси userState в отдельную папку, там создаешь types.ts и переносишь userState.
В types типизируешь State и типизируешь Action.

2023-10-02 05:39 UTC, killank commented on packages/client/src/Redux/userState.tsx
> +    setCurrentProfile: (state, { payload }: { payload: TProfileInfo | null }) =>
Так не очень читается код и Action типизируется так (action: PayloadAction<iAction.setCurrentProfile>).

Прочитать можно тут:
Application Usage.
https://redux.js.org/usage/usage-with-typescript

2023-10-02 05:39 UTC, killank commented on packages/client/src/Redux/store.tsx
> +  reducer: { user: userState },
При дальнейшей работе редьюсеры будут разрастаться и их лучше вынести в отдельный файл rootReducer и описать так:

import {combineReducers} from "redux"
import { userState } from './userState'

export default combineReducers({
    userState,
});

2023-10-02 05:39 UTC, killank commented on packages/client/src/Redux/userState.tsx
> +export const { setCurrentProfile } = slice.actions
Тут лучше экспортировать Actions.

И все Actions разных стейтов лучше экспортировать в отдельном файле в actions.ts.

import {Actions as userState} from "./userState/userState";

export default {
    userState,
};

Таким образом когда ты будешь работать со стейтом в приложении, то тебе достаточно будет импортировать import Actions from 'root/Redux/actions.ts', а не вспоминать, как же называется нужный тебе Action.

2023-10-02 05:39 UTC, killank commented on packages/client/src/Components/userInfo/userInfo.tsx
>          try {
Работа с запросами в Саги

2023-10-02 05:39 UTC, killank commented on packages/client/src/Modules/SignInForm/signInForm.tsx
> +      const profile = await auth.getProfile()
Работа с запросами в Саги

2023-10-02 05:39 UTC, killank commented on packages/client/src/App.tsx
>      try {
Работа с запросами в Саги

2023-10-03 20:57 UTC, burdenkof commented on packages/client/src/Redux/userState.tsx
> +export const { setCurrentProfile } = slice.actions
Все сделал, но не уверен что правильно :(

2023-10-05 14:34 UTC, Dunai1907 approved these changes

2023-10-05 17:50 UTC, killank approved these changes

2023-10-06 05:41 UTC, Olegas commented on packages/client/src/App.tsx
>    const getProfile = async (isLogout = false) => {
Эта функция не используется с флагом true. Это точно нужно? Вообще очень странно, когда функция называется getProfile но в зависимости от флага делает logout. Лучше избегать таких решений.

2023-10-06 05:43 UTC, Olegas commented on packages/client/src/Components/userInfo/userInfo.tsx
> +          dispatch(actions.userState.setCurrentProfile(null))
При внедрении redux имеет смысл собрать вызов API и мутацию состояния в одной действие, используя createAsyncThunk. Иначе сейчас получается, что эти два действия (вызов API и изменение состояния) могут быть вызваны по отдельности что не правильно

2023-10-06 05:43 UTC, Olegas commented on packages/client/src/Modules/SignInForm/signInForm.tsx
> +      dispatch(actions.userState.setCurrentProfile(profile))
Вот это тоже надо объединить через async thunk

2023-10-06 05:43 UTC, Olegas commented on packages/client/src/Modules/SignUpForm/signUpForm.tsx
> +        dispatch(actions.userState.setCurrentProfile(profile))
И здесь та же история

2023-10-06 05:44 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду. Написал подробные комментарии.
Нужно доработать

2023-10-07 16:19 UTC, burdenkof commented on packages/client/src/App.tsx
>    const getProfile = async (isLogout = false) => {
fixed

2023-10-07 16:20 UTC, burdenkof commented on packages/client/src/Components/userInfo/userInfo.tsx
> +          dispatch(actions.userState.setCurrentProfile(null))
сделано

2023-10-07 16:36 UTC, Olegas approved these changes
Работа принята

2023-10-07 19:03 UTC, merged