added logic start&end game
AntonAgaro/Starship pull request #19
Opened 2023-10-03 20:44 UTC by Dunai1907

### Какую задачу решаем
В приложении должны быть реализованы функциональность начала игры (пользователь может начать играть) и функциональность завершения, когда пользователю показывают текущий результат/возможность сыграть ещё/выйти в главное меню.
Добавлена возможность поставить на паузу и продолжить играть

### Скриншоты/видяшка (если есть)

### TBD (если есть)
Когда будет подсчет набранных очей и урон игрока нужно будет допилить
Сейчас добавлены состояния isGameOver и points (их нужно будет изменять)
![Снимок экрана от 2023-10-03 23-41-10](https://github.com/AntonAgaro/Starship/assets/71406480/fa95f9cd-553d-4215-83da-7bba0ca0bde4)
![Снимок экрана от 2023-10-03 23-37-42](https://github.com/AntonAgaro/Starship/assets/71406480/577efff1-bdc4-4b46-a6f6-902c973969cb)
![Снимок экрана от 2023-10-03 23-39-19](https://github.com/AntonAgaro/Starship/assets/71406480/a119c1a2-0653-4ffd-9c80-8ce7053d184b)
)

2023-10-04 13:39 UTC, burdenkof approved these changes

2023-10-05 07:24 UTC, IvanPeleshok commented on packages/client/src/Modules/GameEndModal/gameEndModal.tsx
> +      {isGameOver ? (
Достаточно сложно читать такие тернарники
Предлагаю разбить его следующий образом:

```
const Component = (props) => {
  if (props.isGameOver) {
    return (
      JSX
    )
  }
  
  return props.isGameStopped
    ? ( JSX )
    : ( JSX)
}
```

2023-10-05 07:27 UTC, IvanPeleshok commented on packages/client/src/Pages/Game/game.tsx
> +      if (event.key === 'Escape') {
Название кнопок было бы здорово вынести в перечисление / константу, т.к, полагаю, это ещё будет где-либо ещё переиспользоваться

2023-10-05 07:30 UTC, IvanPeleshok commented on packages/client/src/Pages/Game/game.tsx
> +    navigate('/')
Было бы здорово вынести роуты в константы
Плюсы следующие: 
- человекочитаемость
- переиспользуемость
- предсказуемость

2023-10-05 07:32 UTC, IvanPeleshok commented on packages/client/src/Pages/Game/game.tsx
> +            callback={ctx => {
Предалгаю вынести в метод

Не очень хорошо писать инлайн-колбеки

Читать такое достаточно сложно (вся логика должна содержаться до return JSX)

2023-10-05 07:33 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Замечательно потрудились, нравится)

Есть небольшие замечания, необходима доработка

2023-10-06 09:26 UTC, IvanPeleshok commented on packages/client/src/Pages/Game/game.tsx
> +export enum Buttons {
Предлагаю вынести в отдельный модуль, чтобы была предсказуемость откуда брать общие интерфейсы и константы
Предлагаю пообщаться с командой как и где вам удобнее их определять

2023-10-06 09:28 UTC, IvanPeleshok commented on packages/client/src/Pages/Game/game.tsx
> +  const callback = (ctx: CanvasRenderingContext2D) => {
На данный момент при каждом ререндере компонента, создаётся новая функция
Этого можно избежать с помощью useCallback
https://reactdev.ru/reference/useCallback/#:~:text=useCallback%20%2D%20%D1%8D%D1%82%D0%BE%20%D1%85%D1%83%D0%BA%20React%2C%20%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9,%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%BC%D0%B5%D0%B6%D0%B4%D1%83%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%BD%D1%8B%D0%BC%D0%B8%20%D1%80%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B8%D0%BD%D0%B3%D0%B0%D0%BC%D0%B8.

2023-10-06 09:28 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Критических замечаний не обнаружено

Хорошего дня :)

2023-10-06 11:24 UTC, merged