Sta 27 damage logic
AntonAgaro/Starship pull request #22
Opened 2023-10-09 02:05 UTC by B-rnCorn

STA 27

Реализовать одну из игровых механик, описанных в документе с логикой игры

file:///home/sergey/Videos/Screencasts/Screencast%20from%2009.10.2023%2006:01:02.webm

### TBD 
Босс, щит, доделать завершение игры

2023-10-09 04:18 UTC, AntonAgaro approved these changes

2023-10-09 17:52 UTC, Olegas requested changes
Добрый день.
В текущей реализации есть серьезная проблема. Много где в приложении добавляются слушатели на различные события и запускаются таймеры, которые не останавливаются после окончания игры. Т.к. разрабатывается SPA и после завершения игры можно перейти на другую страницу без перезагрузки приложения, все эти таймеры и обработчики будут срабатывать, накапливаться, вызывать утечки и ошибки в консоли, фатальные отказы приложения. Это нужно исправить. 
Т.к. некоторые из таких обработчиков и таймеров добавлены в рамках выполнения текущей задачи - работу принять не могу

2023-10-10 05:59 UTC, Olegas commented on packages/client/src/Pages/Game/classes/Game.ts
> +    document.addEventListener(GameEventsEnum.AddPlayerBullets, this)
Ого! Я не знал что так можно! Круто )

2023-10-10 06:00 UTC, Olegas approved these changes
Работа принята

2023-10-10 17:08 UTC, merged