Sta 37 add oauth
AntonAgaro/Starship pull request #31
Opened 2023-10-26 00:43 UTC by burdenkof

### Какую задачу решаем
Есть возможность авторизации через Yandex OAuth.

https://ya-praktikum.tech/api/v2/swagger/#/Oauth/post_oauth_yandex

После авторизации будет происходить редирект на страницу с вашим проектом. Чтобы ссылка заработала, отправьте её вашему ментору с просьбой добавить в OAuth. Если тестируете проект локально, в качестве redirect_uri можно использовать http://localhost:3000/ (без слеша в конце, это важно). Ещё варианты портов: 5000, 9000.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-01 09:04 UTC, AntonAgaro approved these changes

2023-11-02 07:42 UTC, IvanPeleshok requested changes
Проделана большая работа
Отлично потрудились!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Modules/OAuth/OAuth.tsx
> +  return props.showButton ? (
В подобное случае, предлагаю так, чтобы лишних элементов не было
```
props.showButton && ( 
  JSX
)
```

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Modules/OAuth/OAuth.tsx
> +  const OAuthAPI = new ApiOAuth()
ApiOAuth() будет создаваться на каждый (ре)ренде компонента
Есть смысл воспользоваться useMemo
https://react.dev/reference/react/useMemo
(Рекомендация)

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Modules/OAuth/OAuth.tsx
> +    <Button type="link" onClick={() => OAuth()}>
Лучше передавать ссылку на функцию в подобном случае, чтобы не плодить инлайн колбеки
```
onClick={OAuth}
```

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Redux/user/userState.tsx
> +          //window.location.href =  window.location.href.split("?")[0]
По принципу YAGNI, если не используется - можно удалить

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Redux/user/userState.tsx
> +          setTimeout(() => (window.location.href = '/signin'), 1000) // Не знаю как правильно из редьюсера послать команду роутеру что бы перейти на страницу авторизации
Там где вызывается санка, дождаться ответа от сервера и в блоке finally вызвать роутинг
```
try {
  await dispatch(thunk)
} finally {
  navigate.push(ROUTE)
}
```

2023-11-02 07:42 UTC, IvanPeleshok commented on packages/client/src/Containers/CheckUserContainer/CheckUserContainer.tsx
> +    const redirect_uri = 'http://localhost:3000'
Предлагаю вынести в переменную окружения, чтобы было удобнее манипулировать

2023-11-02 14:19 UTC, burdenkof commented on packages/client/src/Redux/user/userState.tsx
> +          setTimeout(() => (window.location.href = '/signin'), 1000) // Не знаю как правильно из редьюсера послать команду роутеру что бы перейти на страницу авторизации
С этим есть проблема, я ловлю наличие параметра code в адресной строке до авторизации, и, если есть, делаю запрос к апи практикума. То есть в компоненте, который не обернут в роутер. А иначе роутер видит что авторизации нет, и тут же срабатывает редирект на страницу авторизации(параметр code тут же теряется). Можно ли тут сделать переходы на нужный url без роутера, через window.href?

2023-11-03 07:51 UTC, IvanPeleshok commented on packages/client/src/Components/userInfo/userInfo.tsx
> +          await store.dispatch(asyncLogout())
Ранее не заметил

Предлагаю пользовать хуками редакса (useDispatch)

2023-11-03 07:53 UTC, IvanPeleshok approved these changes
Работа не имеет серьезных замечаний, апрув

Предлагаю поправить небольшое замечание связанное с dispatch

Хорошего дня :)

2023-11-07 19:52 UTC, merged