Sta 47 client forum api
AntonAgaro/Starship pull request #38
Opened 2023-11-10 17:41 UTC by burdenkof

### Какую задачу решаем

Поддержать API форума на клиенте

В проекте полностью реализована функциональность форума. Клиент может: 

 посмотреть все топики, 

 создать новый топик, 

 написать комментарий. 

Добавить необходимую верстку для форума

Все сделано на мок данных, так как апи на стороне сервера пока не смерджено в дев

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-10 17:52 UTC, AntonAgaro approved these changes

2023-11-10 19:34 UTC, Olegas commented on packages/client/src/Api/forum.ts
> +      return await updateTopicStub(data.title, data.topic_id)
return await - эта конструкция не имеет смысла тут. Достаточно просто вернуть результат другой асинхронной функции.

2023-11-10 19:37 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumCommentAddEdit/ForumCommentAddEdit.tsx
> +  })
Из [доументации](https://react.dev/reference/react/useEffect#examples-dependencies) к useEffect: "If you pass no dependency array at all, your Effect runs after every single render (and re-render) of your component."
То есть это вызывается буквально на каждый рендер. Для чего фокусировать поле ввода на каждый рендер? Может быть хотелось сделать это на первом рендере?

2023-11-10 19:38 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +  const [comment_id, setCommentId] = useState(0)
Есть общая конвенция, как называть переменную стейта и ее сеттер. Обычно называют camelCase'ом переменную, и с set - ее сеттер. То есть если у нас setCommentId то переменная должна быть commentId

2023-11-10 19:40 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +      {React.createElement(icon)}
А зачем тут createElement? Ведь можно просто {icon()}

2023-11-10 19:41 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Тут бы лучше добавить else, потому что навигация не обязана прерывать выполнение синхронной функции моментально, dispatch отработает впустую

2023-11-10 19:42 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +      dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Такие последовательности асинхронных действий с redux-стором лучше убрать в async thunk. Компонент диспетчеризует одно действие, все связанные действия внутри thunk

2023-11-10 19:43 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Тут та же история, что и выше. Плюс выбор создавать или обновлять лучше убрать внутрь thunk

2023-11-10 19:44 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +          onClick={() => {
Обработчики событий имеет смысл заворачивать в useCallback - ведь у него не будет (в этом случае) зависимостей и он будет построен один раз (вместо создания новой функции каждый рендер и передачи ее в Button что в свою очередь будет вызывать перестроение Button)

2023-11-10 19:49 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду (написал их в отдельных комментариях)
Нужно доработать.

2023-11-11 14:39 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +      {React.createElement(icon)}
1) Так было в примере в официальной документации antd 2) Просто {icon()} вызывает react-dom.development.js:12056 Uncaught TypeError: icon is not a function. Видимо конкретно этот компонент возвращает что то другое. Без скобок {icon}тоже не работает ругается уже typeScript на несоответствие типов

2023-11-11 15:56 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +      {React.createElement(icon)}
Ок, тогда вопрос снят

2023-11-11 16:06 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
У меня 2 слайса разных, currentComment и currentTopic. Ни как не получается после обнвления камента вызвать обновление топика. То есть   const dispatch = useAppDispatch()
  dispatch(asyncGetTopic( {page, topic_id})) есди я вызываю из asyncThunk из asyncUpdateComment просто игнорится. Как это сделать правильно? Завтра уже дедлайн

2023-11-11 16:07 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Мне придется объединить слайсы что ли? не совсем понимаю зачем тогда они нужны если я не могу из одного обновить другой

2023-11-11 16:34 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Плюс выбор создавать или обновлять лучше убрать внутрь thunk - это сделал. нужно ли объединять слайсы что б все убрать в asyncThunk или есть все таки какой то нормальный способ?

2023-11-11 17:09 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
А почему надо объединять слайсы? Ты же можешь изнутри thunk сделать dispatch другого action, когда у тебя вызов API завершится?

2023-11-11 17:10 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
const dispatch = useAppDispatch()
dispatch(asyncGetTopic( {page, topic_id}))  - описал выше что вызов второго asyncThunk игнорится, список не обновляется

2023-11-11 17:32 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Можешь показать какой код у тебя получается? У тебя в компоненте должен быть один dispatch() дальше внутри функции, которую ты передавал в createAsyncThunk у тебя вызова API а потом после него ты можешь сделать другой dispatch. И получается целиковое бизнес действие - удаление комментария, которое включает в себя 1) само удаление 2) обновление списка топиков/комментариев/whatever

2023-11-11 17:37 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
export const asyncUpdateComment = createAsyncThunk<
  TCommentInfo,
  TUpdateCommentData
>('forum/updateComment', async (data: TUpdateCommentData) => {
  const { author_id, text, topic_id, page } = data
  let response = null

  if (data.comment_id === 0) {
    response = await forumApi.createComment(data)
  } else {
    response = await forumApi.createComment({ author_id, text, topic_id })
  }
  /*   const dispatch = useAppDispatch()


    await  dispatch(asyncGetTopic( {page, topic_id})) - вызов игнорируется! Не знаю что делать*/

  return response as TCommentInfo
})

2023-11-11 17:38 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
```
export const asyncUpdateComment = createAsyncThunk<
  TCommentInfo,
  TUpdateCommentData
>('forum/updateComment', async (data: TUpdateCommentData) => {
  const { author_id, text, topic_id, page } = data
  let response = null

  if (data.comment_id === 0) {
    response = await forumApi.createComment(data)
  } else {
    response = await forumApi.createComment({ author_id, text, topic_id })
  }
  /*   const dispatch = useAppDispatch()


    await  dispatch(asyncGetTopic( {page, topic_id})) - вызов игнорируется! Не знаю что делать*/

  return response as TCommentInfo
})

```

2023-11-11 17:40 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
В компоненте:

```

  const updateComment = async (data: UpdateCommentValues) => {
    setOpenCommentEdit(false)
 
      await dispatch(
        asyncUpdateComment({
          author_id: profile.id,
          comment_id: commentId,
          text: data.text,
          topic_id: props.topic_id,
          page
        })
      )

  }
```

2023-11-11 17:40 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
asyncGetTopic он в другом слайсе...

2023-11-11 17:42 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Если вызывать диспатч asyncGetTopic  из компонента то все работает как надо
```
  const updateComment = async (data: UpdateCommentValues) => {
    setOpenCommentEdit(false)
 
      await dispatch(
        asyncUpdateComment({
          author_id: profile.id,
          comment_id: commentId,
          text: data.text,
          topic_id: props.topic_id,
          page
        })
      )
      await dispatch(asyncGetTopic({page, topic_id: props.topic_id}))
  }
```

2023-11-11 17:46 UTC, Olegas commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Посмотри вот тут https://redux-toolkit.js.org/api/createAsyncThunk
У тебя в функции создания thunk вторым аргументом идет thunkApi. Именно из него надо взять dispatch а не из useAppDispatch. И тогда все должно взлететь

2023-11-11 18:52 UTC, burdenkof commented on packages/client/src/Modules/Forum/ForumTopic/forumTopic.tsx
> +    dispatch(asyncGetTopic({ page, topic_id: props.topic_id }))
Все взлетело, Вы были правы

2023-11-12 05:50 UTC, Olegas commented on packages/client/src/Redux/forum/currentCommentState.ts
> +import { useAppDispatch } from '../../Hooks/reduxHooks'
Не забудь убрать этот импорт, он тут не используется. Еще можно настроить соответствующее правило ESLint (будет падать если есть неиспользуемые импорты)

2023-11-12 05:51 UTC, Olegas approved these changes
Работа принята

2023-11-12 14:37 UTC, merged