theme switching BE
AntonAgaro/Starship pull request #39
Opened 2023-11-12 10:31 UTC by B-rnCorn

### STA-46 Переключение темы (бэкенд)

Добавил модели для хранения темы и выбранной темы и апишки для них.
Для выбранной темы незарегистрированного или невошедшего пользователя будет использоваться токен, созданный через nanoid на клиенте, после входа используется логин.

### TBD
Интеграция с FE после мержа клиентской части в девелоп
Миграции дефолтных тем, чтобы не делать inesert вручную

2023-11-12 17:23 UTC, IvanPeleshok requested changes
Проделана большая работа!
Здорово постарались!

Обращаю внимание, что работа не может быть принята без апрува хотя бы одно члена вашей команды, покажите её обязательно перед отправкой на ревью в практикум, а также поправьте линтер

Есть некоторые замечания, предлагаю поправить (замечания масштабируйте на весь PR, т.к не дублировал их для всех похожих кейсов)

Хорошего дня :)

2023-11-12 17:23 UTC, IvanPeleshok commented on packages/server/controllers/ChosenTheme.ts
> +class ChosenTheme {
Почему бы не назвать просто Theme? 

Наименование не очень гибкое для понимания

2023-11-12 17:23 UTC, IvanPeleshok commented on packages/server/controllers/ChosenTheme.ts
> +        user_theme_token: this.user_theme_token as string,
Почему бы не прокидывать значения с помощью аргументов функцию?

2023-11-12 17:23 UTC, IvanPeleshok commented on packages/server/routes/theme.ts
> +    const availableThemes = await new Theme({}).getAllThemes()
Предлагаю сделать методы статическими, тогда не будет необходимости создавать экземпляр класса (так будет читаемее и очевиднее)

Если необходимо прокинуть значения - делать это через аргументы

2023-11-12 17:23 UTC, IvanPeleshok commented on packages/server/routes/theme.ts
> +    }).getChosenThemeByThemeToken
Совет аналогичен предыдущим + необходим вызов метода

2023-11-12 17:23 UTC, IvanPeleshok commented on packages/server/routes/theme.ts
> +    res.json(chosenTheme)
Предлагаю указывать статус ответа (для созданных ресурсов - 201)
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/201

2023-11-12 19:06 UTC, burdenkof requested changes
Тесты упали. Нужно поправить

2023-11-12 21:35 UTC, burdenkof approved these changes

2023-11-13 15:59 UTC, IvanPeleshok approved these changes
Отлично потрудились!

Поздравляю, работа принята!

Хорошего дня :)

2023-11-13 20:28 UTC, merged